In [1]:
import torch

In [2]:
x = torch.randn(3,1)

In [3]:
x

tensor([[ 2.3491],
        [ 1.4651],
        [-0.6256]])

In [4]:
y = x.data

In [5]:
z = x.clone()

In [10]:
x += 1.0

In [11]:
x

tensor([[3.4491],
        [2.5651],
        [0.4744]])

In [12]:
y

tensor([[3.4491],
        [2.5651],
        [0.4744]])

In [13]:
z

tensor([[ 2.3491],
        [ 1.4651],
        [-0.6256]])